x-superset-image: &superset-image computablefacts/superset-for-swarm-custom:1.5.2.7
x-superset-env: &superset-env
  # database configurations
  - DATABASE_DIALECT=mysql+mysqlconnector
  - DATABASE_HOST=host.docker.internal
  - DATABASE_PORT=3306
  - DATABASE_USER=__DB_USER__
  - DATABASE_PASSWORD=__DB_PWD__
  - DATABASE_DB=__DB_NAME__

  - REDIS_HOST=redis
  - REDIS_PORT=6379

  - SECRET_KEY=MonSecretKEY_a_changer_apres_mes_tests
  - FLASK_ENV=production
  - SUPERSET_ENV=production
  - SUPERSET_LOAD_EXAMPLES=no
  - CYPRESS_CONFIG=false
  - SUPERSET_PORT=8088
  
  - SCREENSHOT_LOCATE_WAIT=20
  - SCREENSHOT_LOAD_WAIT=120
  - SCREENSHOT_SELENIUM_HEADSTART=6
  - SCREENSHOT_SELENIUM_ANIMATION_WAIT=10

  - CELERY_WORKER_LOG_LEVEL=INFO


version: "3.7"

networks:
  redis-net:
  selenium-net:
  traefik-public:
    external: true
  dev-mysql-net:
    external: true
  staging-mysql-net:
    external: true
  prod-mysql-net:
    external: true

services:
  redis:
    image: redis:6.2
    command: bash -c "redis-server --save "" --maxmemory-policy allkeys-lru --loglevel warning"
    networks:
      redis-net:
        aliases:
          - redis
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 64M

  superset:
    image: *superset-image
    environment: *superset-env
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      selenium-net:
        aliases:
          - test-patrick
      redis-net:
    ports:
    - target: 8088
      host_ip: 127.0.0.1
      published: "__PORT__"
      protocol: tcp
      mode: host

  superset-init:
    image: *superset-image
    environment: *superset-env
    command: ["/app/docker/docker-init.sh"]
    healthcheck:
      disable: true
    user: "root"
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - redis-net
    deploy:
      restart_policy:
        condition: on-failure

  superset-worker:
    image: *superset-image
    environment: *superset-env
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    healthcheck:
      disable: true
    user: "root"
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - selenium-net
      - redis-net

  superset-worker-beat:
    image: *superset-image
    environment: *superset-env
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    healthcheck:
      disable: true
    user: "root"
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - redis-net
