#!/bin/bash

# Add rules to allows Docker containers to reach MySQL on port 3306
# For explanations about CIDR used, see: https://straz.to/2021-09-08-docker-address-pools/
iptables -A INPUT -p tcp --dport 3306 -s 172.17.0.0/12 -j ACCEPT
iptables -A INPUT -p tcp --dport 3306 -s 192.168.0.0/16 -j ACCEPT
